name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  nuts:
    runs-on: ubuntu-latest
    env:
      TESTKIT_AUTH_URL: ${{ secrets.TESTKIT_AUTH_URL }}
      SF_USE_GENERIC_UNIX_KEYCHAIN: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install -g @salesforce/cli@2.139.6
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test:nuts
