name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - run: if [ -z "$TESTKIT_AUTH_URL" ]; then echo "NOT SET"; else echo "len=${#TESTKIT_AUTH_URL}"; fi
        env:
          TESTKIT_AUTH_URL: ${{ secrets.TESTKIT_AUTH_URL }}

  nuts:
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
      nodeVersion: '20'
