name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "auth_url_set=${{ secrets.TESTKIT_AUTH_URL != '' }}"
          echo "hub_username_set=${{ secrets.TESTKIT_HUB_USERNAME != '' }}"
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  nuts:
    needs: unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets:
      TESTKIT_AUTH_URL: ${{ secrets.TESTKIT_AUTH_URL }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
